# --------------------------------------------------------------------------
# THIS FILE IS AUTOGENERATED - DO NOT EDIT MANUALLY
#
# Source: Containerfile.j2
# --------------------------------------------------------------------------

ARG BASE_VERSION=15

ARG UPSTREAM_URL="https://api.github.com/repos/Kozea/Radicale/releases/latest"
ARG UPSTREAM_JQ=".tag_name"

FROM ghcr.io/daemonless/base:${BASE_VERSION} AS builder

ARG UPSTREAM_URL
ARG UPSTREAM_JQ
ARG DEPENDENCIES=bcrypt

# Determine latest version
RUN mkdir /app && \
    fetch -qo - "${UPSTREAM_URL}" | jq -r "${UPSTREAM_JQ}" | sed -n 's/v\(.*\)/\1/p' > /app/version
    
    # Install dependencies
    RUN pkg update && \
    pkg install -y \
    FreeBSD-clang \
    FreeBSD-toolchain \
    FreeBSD-clibs-dev \
    FreeBSD-runtime-dev \
    FreeBSD-utilities-dev \
    FreeBSD-libexecinfo-dev \
    rust \
    python312 && \
    pkg clean -ay && \
    rm -rf /var/cache/pkg/* /var/db/pkg/repos/*
    
RUN python3.12 -m venv /app/venv && \
/app/venv/bin/pip install --no-cache-dir "Radicale[${DEPENDENCIES}] @ https://github.com/Kozea/Radicale/archive/v$(cat /app/version).tar.gz"


FROM ghcr.io/daemonless/base:${BASE_VERSION}

ARG FREEBSD_ARCH=amd64
ARG PACKAGES="python312"

ARG UPSTREAM_URL
ARG UPSTREAM_JQ

LABEL org.opencontainers.image.title="OpenCloud-Radicale" \
      org.opencontainers.image.description="A simple CalDAV (calendar) and CardDAV (contact) server." \
      org.opencontainers.image.source="https://github.com/daemonless/opencloud-radicale" \
      org.opencontainers.image.url="https://radicale.org/" \
      org.opencontainers.image.licenses="GPL-3.0" \
      org.opencontainers.image.vendor="daemonless" \
      org.opencontainers.image.authors="daemonless" \
      io.daemonless.category="Utilities" \
      io.daemonless.port="5232" \
      io.daemonless.arch="${FREEBSD_ARCH}" \
      io.daemonless.upstream-url="${UPSTREAM_URL}" \
      io.daemonless.upstream-jq="${UPSTREAM_JQ}" \
      io.daemonless.packages="${PACKAGES}"
      

# Install dependencies
RUN pkg update && \
    pkg install -y ${PACKAGES} && \
    pkg clean -ay && \
    rm -rf /var/cache/pkg/* /var/db/pkg/repos/*

# Copy radicale from builder
COPY --chown=bsd:bsd --from=builder /app/version /app/venv/ /app

# Copy root filesystem
COPY root/ /

# Set permissions
RUN mkdir -p /config/collections && \
    chown -R bsd:bsd /app /config && \
    chmod +x /etc/cont-init.d/* /etc/services.d/radicale/run /healthz

# Set default path for configuration file
ENV RADICALE_CONFIG=/config/radicale.conf

# Expose
EXPOSE 5232

# Volumes
VOLUME /config