#!/bin/sh

if [ ! -f /config/radicale.conf ]; then
    cp /etc/templates/radicale.conf /config/radicale.conf
    
    chown bsd:bsd /config/authelia.yml

    echo "[radicale-init] Created default radicale.conf"
fi